"""'image_migration'

Revision ID: b29a1917c901
Revises: cb26946004bb
Create Date: 2021-06-06 07:35:38.187060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29a1917c901'
down_revision = 'cb26946004bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_path')
    # ### end Alembic commands ###
